apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: docker-registry-ingress
  namespace: docker-registry
spec:
  routes:
    - match: Host(`registry.<YOUR_DOMAIN>.com`) # Update this with your own domain
      kind: Rule
      middlewares: [ ]
      services:
        - kind: Service
          name: docker-registry-service
          namespace: docker-registry
          port: 5000

